import {
  AngularIcon,
  Css3Icon,
  Html5Icon,
  JavaIcon,
  NodeIcon,
  PythonIcon,
  ReactIcon,
  RustIcon,
  SvelteIcon,
  VueIcon,
  TypescriptIcon,
  JavascriptIcon,
  NextjsIcon,
  ViteIcon,
  TailwindIcon,
  BootstrapIcon,
  JqueryIcon,
  JestIcon,
  CypressIcon,
  StorybookIcon,
  ReduxIcon,
  GraphqlIcon,
  WebpackIcon,
  BabelIcon,
  GatsbyIcon,
  EmberIcon,
  SassIcon,
  LessIcon,
  PlaywrightIcon,
  ThreejsIcon,
  ElmIcon,
  PreactIcon,
  AlpineIcon,
  LitIcon,
  SolidIcon,
  DartIcon,
  CoffeescriptIcon,
  PurescriptIcon,
  ReasonMLIcon,
  StimulusIcon,
  ClojurescriptIcon,
  FsharpIcon,
  HaxeIcon,
  BackboneIcon,
  KnockoutIcon,
  PolymerIcon,
  AureliaIcon,
  MeteorIcon,
  D3Icon,
  ChartjsIcon,
  GoIcon,
  CsharpIcon,
  AspNetIcon,
  PhpIcon,
  LaravelIcon,
  RubyIcon,
  RailsIcon,
  ExpressIcon,
  PostgresqlIcon,
  MongodbIcon,
  DjangoIcon,
  FlaskIcon,
  SpringBootIcon,
  KotlinIcon,
  NestjsIcon,
  ElixirIcon,
  PhoenixIcon,
  MysqlIcon,
  RedisIcon,
  DockerIcon,
  FirebaseIcon,
  SupabaseIcon,
  NginxIcon,
  ApacheKafkaIcon,
  RabbitmqIcon,
  KubernetesIcon,
  TerraformIcon,
  GrpcIcon,
  SolidityIcon,
  ScalaIcon,
  AkkaIcon,
  CassandraIcon,
  ElasticsearchIcon,
  PrometheusIcon,
} from '@/components/icons';
import type { ComponentType } from 'react';

export interface Technology {
  name: string;
  icon: ComponentType<React.SVGProps<SVGSVGElement>>;
  description: string;
  type: 'Framework' | 'Linguagem' | 'Biblioteca' | 'Ferramenta' | 'Plataforma';
  detailedDescription?: string;
  examples?: string;
  difficulty: number;
  popularity: number;
}

export const frontendTechnologies: Technology[] = [
  {
    name: 'React',
    icon: ReactIcon,
    description:
      'Uma biblioteca JavaScript para construir interfaces de usuário ricas e interativas.',
    type: 'Biblioteca',
    detailedDescription: 'O React é uma biblioteca JavaScript declarativa, eficiente e flexível para criar interfaces de usuário (UI). Ele permite a composição de UIs complexas a partir de pequenas e isoladas peças de código chamadas "componentes". O React utiliza um DOM virtual para otimizar o desempenho, atualizando apenas as partes da página que foram alteradas.',
    examples: 'Facebook, Instagram, WhatsApp, Netflix, Airbnb, The New York Times.',
    difficulty: 6.5,
    popularity: 9.8,
  },
  {
    name: 'Vue.js',
    icon: VueIcon,
    description:
      'Um framework progressivo, conhecido por sua simplicidade e excelente documentação.',
    type: 'Framework',
    detailedDescription: 'Vue.js é um framework progressivo para a construção de interfaces de usuário. Diferente de outros frameworks monolíticos, Vue foi projetado desde o início para ser adotável incrementalmente. A biblioteca principal foca apenas na camada de visualização, e é fácil de integrar com outras bibliotecas ou projetos existentes.',
    examples: 'Alibaba, Xiaomi, Adobe, Gitlab, Behance.',
    difficulty: 5.5,
    popularity: 8.5,
  },
  {
    name: 'Angular',
    icon: AngularIcon,
    description:
      'Uma plataforma robusta do Google para construir aplicações web complexas e em larga escala.',
    type: 'Plataforma',
    detailedDescription: 'Angular é uma plataforma e framework para construir aplicações de página única (SPA) usando HTML e TypeScript. Ele é mantido pelo Google e por uma comunidade de indivíduos e corporações. Angular é conhecido por ser uma solução completa, oferecendo tudo o que é necessário para construir aplicações complexas, desde roteamento até gerenciamento de estado.',
    examples: 'Google, Microsoft (Office Home), IBM, PayPal, Upwork, The Guardian.',
    difficulty: 8.0,
    popularity: 8.2,
  },
  {
    name: 'Svelte',
    icon: SvelteIcon,
    description:
      'Um compilador que transforma seu código em JavaScript vanilla, resultando em apps mais rápidos.',
    type: 'Framework',
    detailedDescription: 'Svelte é uma abordagem radicalmente nova para construir interfaces de usuário. Enquanto frameworks tradicionais como React e Vue fazem a maior parte do seu trabalho no navegador, Svelte transfere esse trabalho para uma etapa de compilação que acontece quando você constrói seu aplicativo. Isso resulta em código JavaScript imperativo altamente otimizado, proporcionando um desempenho excepcional.',
    examples: 'Stone, The New York Times, 1Password, Philips, GoDaddy.',
    difficulty: 5.0,
    popularity: 7.0,
  },
  {
    name: 'HTML5',
    icon: Html5Icon,
    description:
      'A linguagem de marcação padrão para criar páginas da web e aplicações web.',
    type: 'Linguagem',
    detailedDescription: 'HTML5 é a espinha dorsal da web. É a linguagem de marcação usada para estruturar o conteúdo de uma página, como textos, imagens, links e vídeos. A versão 5 introduziu novas tags semânticas (<article>, <section>), suporte a multimídia (<audio>, <video>), e APIs para funcionalidades complexas como armazenamento local e gráficos 2D/3D (Canvas, WebGL).',
    examples: 'Praticamente todos os sites na internet, incluindo Google, YouTube, Amazon.',
    difficulty: 1.0,
    popularity: 10.0,
  },
  {
    name: 'CSS3',
    icon: Css3Icon,
    description:
      'A linguagem de folha de estilo usada para descrever a apresentação de um documento escrito em HTML.',
    type: 'Linguagem',
    detailedDescription: 'CSS (Cascading Style Sheets) é a linguagem que usamos para estilizar um documento HTML. Ela descreve como os elementos HTML devem ser exibidos na tela. O CSS3, a versão mais recente, trouxe recursos poderosos como Flexbox e Grid para layouts complexos, animações, transições, e a capacidade de criar designs responsivos que se adaptam a diferentes tamanhos de tela.',
    examples: 'Utilizado em conjunto com HTML em todos os sites visualmente estilizados.',
    difficulty: 2.5,
    popularity: 10.0,
  },
  {
    name: 'TypeScript',
    icon: TypescriptIcon,
    description:
      'Um superconjunto de JavaScript que adiciona tipagem estática opcional.',
    type: 'Linguagem',
    detailedDescription: 'TypeScript é uma linguagem de programação desenvolvida pela Microsoft que adiciona tipos estáticos ao JavaScript. Isso ajuda a detectar erros durante o desenvolvimento, em vez de em tempo de execução. O código TypeScript é transpilado para JavaScript puro, o que o torna compatível com qualquer navegador ou ambiente que execute JS. Adoção massiva em projetos grandes para melhorar a manutenibilidade e escalabilidade.',
    examples: 'Angular, Slack, Asana, Visual Studio Code (que é construído com ele).',
    difficulty: 7.0,
    popularity: 9.5,
  },
  {
    name: 'JavaScript',
    icon: JavascriptIcon,
    description:
      'A linguagem de programação fundamental da web, executada no navegador do cliente.',
    type: 'Linguagem',
    detailedDescription: 'JavaScript é uma linguagem de programação de alto nível que, junto com HTML e CSS, é uma das tecnologias centrais da World Wide Web. Ela permite criar páginas web interativas e é uma parte essencial das aplicações web. Originalmente apenas do lado do cliente, hoje também é amplamente utilizada no lado do servidor com Node.js.',
    examples: '99% dos sites modernos, incluindo Facebook, Google, e todos os baseados em frameworks como React, Vue e Angular.',
    difficulty: 6.0,
    popularity: 10.0,
  },
  {
    name: 'Next.js',
    icon: NextjsIcon,
    description:
      'Um framework React para produção, com renderização estática e no lado do servidor.',
    type: 'Framework',
    detailedDescription: 'Next.js é um framework React que oferece uma estrutura para construir aplicações web otimizadas para desempenho. Ele fornece funcionalidades prontas para uso, como renderização no lado do servidor (SSR), geração de sites estáticos (SSG), otimização de imagens, roteamento baseado em sistema de arquivos e suporte para API routes, simplificando o desenvolvimento de aplicações React completas e performáticas.',
    examples: 'Vercel, TikTok, Hulu, Twitch, Nike.',
    difficulty: 7.5,
    popularity: 9.2,
  },
  {
    name: 'Vite',
    icon: ViteIcon,
    description:
      'Uma ferramenta de build moderna que oferece um desenvolvimento mais rápido e ágil.',
    type: 'Ferramenta',
    detailedDescription: 'Vite é uma ferramenta de frontend de última geração que visa proporcionar uma experiência de desenvolvimento significativamente mais rápida para projetos web modernos. Ele consiste em duas partes principais: um servidor de desenvolvimento que oferece recarregamento de módulo instantâneo (HMR) e um comando de build que empacota seu código com Rollup, pré-configurado para produzir ativos estáticos altamente otimizados.',
    examples: 'Amplamente utilizado pela comunidade Vue.js e Svelte; adotado em muitos projetos React e de outras bibliotecas.',
    difficulty: 4.5,
    popularity: 8.0,
  },
  {
    name: 'Tailwind CSS',
    icon: TailwindIcon,
    description:
      'Um framework CSS "utility-first" para criar designs customizados rapidamente.',
    type: 'Framework',
    detailedDescription: 'Tailwind CSS é um framework CSS que adota uma abordagem "utility-first". Em vez de classes semânticas como `.card`, você compõe interfaces usando classes utilitárias como `p-4`, `flex`, `text-xl`. Isso permite criar designs altamente customizados sem sair do seu HTML e sem escrever CSS personalizado, acelerando o desenvolvimento e mantendo a consistência.',
    examples: 'Netflix, Shopify (Polaris), GitHub, Heroku.',
    difficulty: 3.5,
    popularity: 9.0,
  },
  {
    name: 'Bootstrap',
    icon: BootstrapIcon,
    description:
      'Framework popular para desenvolver sites responsivos e mobile-first.',
    type: 'Framework',
    detailedDescription: 'Bootstrap é um dos frameworks CSS mais antigos e populares. Ele fornece um conjunto de componentes de interface (botões, formulários, modais) e um sistema de grid responsivo, permitindo que desenvolvedores criem rapidamente sites com aparência consistente e que funcionam bem em todos os dispositivos. É uma ótima opção para prototipagem rápida e projetos que não exigem um design único.',
    examples: 'Twitter (onde foi criado), Spotify, LinkedIn, e inúmeros temas e templates na web.',
    difficulty: 2.0,
    popularity: 7.5,
  },
  {
    name: 'jQuery',
    icon: JqueryIcon,
    description:
      'Uma biblioteca JavaScript clássica que simplifica a manipulação de HTML e eventos.',
    type: 'Biblioteca',
    detailedDescription: 'jQuery é uma biblioteca JavaScript rápida, pequena e rica em recursos. Ela simplifica muito coisas como travessia e manipulação de documentos HTML, manipulação de eventos, animação e Ajax. Embora seu uso tenha diminuído com o surgimento de frameworks modernos como React e Vue, ela ainda é encontrada em muitos sites e sistemas legados, e sua influência na web é inegável.',
    examples: 'WordPress, muitos sites mais antigos e alguns projetos que precisam de manipulação direta do DOM sem um framework completo.',
    difficulty: 2.0,
    popularity: 5.0,
  },
  {
    name: 'Jest',
    icon: JestIcon,
    description: 'Um framework de teste de JavaScript com foco na simplicidade.',
    type: 'Framework',
    detailedDescription: 'Jest é um framework de teste de JavaScript mantido pelo Facebook, projetado para garantir a correção de qualquer base de código JavaScript. Ele permite escrever testes com uma sintaxe acessível, familiar e rica em recursos. Jest oferece uma solução completa, com corredor de testes, biblioteca de asserções e capacidade de mocking (simulação) integrados.',
    examples: 'Facebook, Twitter, Airbnb, e é o corredor de testes padrão para projetos Create React App.',
    difficulty: 6.0,
    popularity: 8.8,
  },
  {
    name: 'Cypress',
    icon: CypressIcon,
    description:
      'Ferramenta de teste de ponta a ponta para tudo que roda em um navegador.',
    type: 'Ferramenta',
    detailedDescription: 'Cypress é uma ferramenta de teste de frontend de última geração construída para a web moderna. Ele permite escrever testes de ponta a ponta (E2E), testes de integração e testes de unidade. Sua arquitetura única o executa no mesmo ciclo de execução que sua aplicação, proporcionando controle total, velocidade e feedback visual em tempo real.',
    examples: 'Usado por empresas como Disney, DHL, GoDaddy para garantir a qualidade de suas aplicações web.',
    difficulty: 7.0,
    popularity: 7.5,
  },
  {
    name: 'Storybook',
    icon: StorybookIcon,
    description:
      'Uma ferramenta para desenvolver componentes de UI de forma isolada e organizada.',
    type: 'Ferramenta',
    detailedDescription: 'Storybook é um ambiente de desenvolvimento de frontend para componentes de UI. Ele permite que você navegue por uma "biblioteca" de componentes, veja os diferentes estados de cada um e desenvolva componentes de forma interativa e isolada do resto da aplicação. Isso melhora a organização, a reutilização e o teste dos componentes.',
    examples: 'Adobe, Uber, BBC, The Guardian, e a maioria das empresas com um sistema de design robusto.',
    difficulty: 5.0,
    popularity: 8.0,
  },
  {
    name: 'Redux',
    icon: ReduxIcon,
    description:
      'Uma biblioteca previsível para gerenciamento de estado em aplicações JavaScript.',
    type: 'Biblioteca',
    detailedDescription: 'Redux é um contêiner de estado previsível para aplicações JavaScript. Ele ajuda a escrever aplicações que se comportam de forma consistente, executadas em diferentes ambientes (cliente, servidor e nativo) e são fáceis de testar. Com Redux, o estado de toda a sua aplicação é armazenado em um único objeto (store), tornando mais fácil entender e depurar o fluxo de dados.',
    examples: 'Amplamente utilizado em grandes aplicações React, embora alternativas como Context API e Zustand tenham ganhado popularidade.',
    difficulty: 7.8,
    popularity: 7.0,
  },
  {
    name: 'GraphQL',
    icon: GraphqlIcon,
    description:
      'Uma linguagem de consulta para APIs que permite aos clientes pedir exatamente o que precisam.',
    type: 'Linguagem',
    detailedDescription: 'GraphQL é uma linguagem de consulta para APIs e um tempo de execução para atender a essas consultas com seus dados existentes. Ele oferece uma alternativa mais eficiente e poderosa às arquiteturas REST tradicionais. Com GraphQL, o cliente especifica exatamente quais dados ele precisa, evitando o excesso (over-fetching) ou a falta (under-fetching) de dados.',
    examples: 'Facebook (onde foi criado), GitHub, Pinterest, Shopify, Coursera.',
    difficulty: 7.2,
    popularity: 8.5,
  },
  {
    name: 'Webpack',
    icon: WebpackIcon,
    description:
      'Um empacotador de módulos estáticos para aplicações JavaScript modernas.',
    type: 'Ferramenta',
    detailedDescription: 'Webpack é uma ferramenta de build que empacota módulos JavaScript para uso em um navegador. Ele pode transformar, agrupar ou empacotar praticamente qualquer recurso ou ativo. Ele pega módulos com dependências e gera ativos estáticos representando esses módulos. É altamente configurável e foi a base para muitas ferramentas de linha de comando como Create React App.',
    examples: 'Ferramenta de base para Create React App, Vue CLI e muitos outros projetos complexos.',
    difficulty: 8.5,
    popularity: 7.5,
  },
  {
    name: 'Babel',
    icon: BabelIcon,
    description:
      'Um compilador JavaScript que permite usar as versões mais recentes da linguagem.',
    type: 'Ferramenta',
    detailedDescription: 'Babel é uma cadeia de ferramentas usada principalmente para converter código ECMAScript 2015+ (as versões mais recentes do JavaScript) em uma versão compatível com versões anteriores de JavaScript em navegadores ou ambientes atuais e mais antigos. Isso permite que os desenvolvedores usem os recursos mais modernos da linguagem sem se preocupar com a compatibilidade.',
    examples: 'Usado por quase todo o ecossistema JavaScript moderno, incluindo React, Vue, e Next.js.',
    difficulty: 5.0,
    popularity: 8.5,
  },
  {
    name: 'Gatsby',
    icon: GatsbyIcon,
    description:
      'Um framework baseado em React para criar sites e aplicativos rápidos e otimizados.',
    type: 'Framework',
    detailedDescription: 'Gatsby é um gerador de sites estáticos (SSG) de código aberto baseado em React. Ele ajuda os desenvolvedores a construir sites e aplicativos extremamente rápidos, combinando o melhor do React com a performance de sites estáticos pré-renderizados. Gatsby puxa dados de qualquer fonte (CMSs, Markdown, APIs) e os usa para gerar páginas HTML estáticas na etapa de build.',
    examples: 'Sites de marketing, blogs e documentações, como o site da DigitalOcean e da Braun.',
    difficulty: 7.5,
    popularity: 6.5,
  },
  {
    name: 'Ember.js',
    icon: EmberIcon,
    description:
      'Um framework JavaScript opinativo para a criação de aplicações web ambiciosas.',
    type: 'Framework',
    detailedDescription: 'Ember.js é um framework JavaScript produtivo e testado em batalha para construir aplicações web modernas. Ele inclui tudo o que você precisa para construir interfaces de usuário ricas que funcionam em qualquer dispositivo. Ember segue a convenção sobre configuração, o que significa que ele toma decisões para você, permitindo que você se concentre na construção do seu aplicativo.',
    examples: 'Apple Music, LinkedIn, Square, e Heroku.',
    difficulty: 8.2,
    popularity: 4.0,
  },
  {
    name: 'Sass',
    icon: SassIcon,
    description:
      'Um pré-processador CSS que adiciona recursos como variáveis, aninhamento e mixins.',
    type: 'Linguagem',
    detailedDescription: 'Sass (Syntactically Awesome Style Sheets) é um pré-processador CSS que estende a linguagem CSS. Ele permite o uso de recursos que não existem no CSS puro, como variáveis, aninhamento de seletores, mixins (funções), herança e muito mais. O código Sass é compilado em CSS padrão para que o navegador possa interpretá-lo.',
    examples: 'Bootstrap (versões mais antigas), e muitos sistemas de design e projetos que precisam de CSS escalável.',
    difficulty: 4.0,
    popularity: 8.0,
  },
  {
    name: 'Less',
    icon: LessIcon,
    description:
      'Outro pré-processador CSS popular que estende a funcionalidade do CSS.',
    type: 'Linguagem',
    detailedDescription: 'Less (Leaner Style Sheets) é um pré-processador CSS que, assim como o Sass, permite escrever CSS de uma forma mais programática. Ele adiciona recursos como variáveis, mixins, funções e operações. A sintaxe do Less é muito semelhante à do CSS, o que torna sua adoção bastante fácil para quem já conhece CSS.',
    examples: 'Bootstrap (nas suas primeiras versões) e muitos outros frameworks e projetos.',
    difficulty: 3.8,
    popularity: 5.5,
  },
  {
    name: 'Playwright',
    icon: PlaywrightIcon,
    description:
      'Framework de teste de ponta a ponta da Microsoft para automação web confiável.',
    type: 'Framework',
    detailedDescription: 'Playwright é uma biblioteca Node.js para automatizar navegadores baseados em Chromium, Firefox e WebKit com uma única API. Ele permite testes de ponta a ponta (E2E) confiáveis, que são rápidos, capazes e sempre verdes. Playwright é conhecido por sua capacidade de lidar com aplicações modernas de página única e por sua excelente ferramenta de depuração.',
    examples: 'Usado por equipes de QA na Microsoft e em outras empresas para automação de testes robustos.',
    difficulty: 7.2,
    popularity: 7.0,
  },
  {
    name: 'Three.js',
    icon: ThreejsIcon,
    description:
      'Uma biblioteca 3D para JavaScript que facilita a criação de gráficos e animações na web.',
    type: 'Biblioteca',
    detailedDescription: 'Three.js é uma biblioteca JavaScript multiplataforma e de fácil utilização para criar e exibir gráficos 3D animados em um navegador da web usando WebGL. Ele simplifica o processo complexo de trabalhar diretamente com a API WebGL, fornecendo um conjunto de abstrações como cenas, luzes, sombras, materiais e câmeras.',
    examples: 'Sites interativos, experiências imersivas, jogos e visualizações de produtos em 3D.',
    difficulty: 8.8,
    popularity: 7.2,
  },
  {
    name: 'Elm',
    icon: ElmIcon,
    description:
      'Uma linguagem funcional que compila para JavaScript, focada em confiabilidade e sem erros em tempo de execução.',
    type: 'Linguagem',
    detailedDescription: 'Elm é uma linguagem de programação funcional para criar interfaces de usuário baseadas na web de forma declarativa. Elm compila para JavaScript e é famoso por sua garantia de "nenhum erro em tempo de execução". Seu compilador amigável e arquitetura simples ajudam a criar aplicações robustas e fáceis de manter.',
    examples: 'Empresas que priorizam a robustez e a ausência de bugs, como a NoRedInk.',
    difficulty: 8.5,
    popularity: 3.0,
  },
  {
    name: 'Preact',
    icon: PreactIcon,
    description:
      'Uma alternativa rápida e leve ao React, com a mesma API moderna e apenas 3kB de tamanho.',
    type: 'Biblioteca',
    detailedDescription: 'Preact é uma biblioteca JavaScript que se apresenta como uma alternativa rápida ao React, com o mesmo ES6 API. Ele é pequeno em tamanho (cerca de 3kB), mas oferece a maioria dos recursos do React, incluindo componentes e um DOM virtual. É uma excelente escolha para projetos onde o desempenho e o tamanho do pacote são críticos, como aplicações móveis.',
    examples: 'Uber, Lyft, The Financial Times, e vários widgets e aplicações leves.',
    difficulty: 6.0,
    popularity: 6.0,
  },
  {
    name: 'Alpine.js',
    icon: AlpineIcon,
    description:
      'Um framework JavaScript minimalista para compor comportamento reativo diretamente no seu HTML.',
    type: 'Framework',
    detailedDescription: 'Alpine.js oferece a natureza reativa e declarativa de grandes frameworks como Vue ou React por um custo muito menor. Ele permite que você "polvilhe" comportamento em sua marcação HTML sem a necessidade de uma etapa de build. É como o "Tailwind para JavaScript", permitindo que você escreva a maior parte da sua lógica diretamente no HTML.',
    examples: 'Ideal para sites onde você precisa de pequenas ilhas de interatividade, sem um framework pesado.',
    difficulty: 3.0,
    popularity: 5.8,
  },
  {
    name: 'Lit',
    icon: LitIcon,
    description:
      'Uma biblioteca simples para construir componentes web rápidos e leves que funcionam em qualquer framework.',
    type: 'Biblioteca',
    detailedDescription: 'Lit (anteriormente LitElement) é uma biblioteca do Google para construir componentes web rápidos e leves. Ele se baseia nos padrões da web (Web Components), o que significa que os componentes que você cria com Lit são nativos do navegador e podem ser usados em qualquer página HTML, com qualquer framework (React, Vue, etc.) ou sem nenhum framework.',
    examples: 'Usado internamente no Google para construir partes do YouTube e outras propriedades.',
    difficulty: 6.8,
    popularity: 5.5,
  },
  {
    name: 'SolidJS',
    icon: SolidIcon,
    description:
      'Um framework declarativo para construir interfaces de usuário que compila para JavaScript otimizado e reativo.',
    type: 'Framework',
    detailedDescription: 'SolidJS é um framework JavaScript para criar interfaces de usuário que se destaca pelo seu desempenho. Ele usa uma abordagem de reatividade refinada, o que significa que ele atualiza o DOM diretamente em resposta a mudanças de estado, sem a necessidade de um DOM virtual. O resultado são aplicações extremamente rápidas e eficientes.',
    examples: 'Aplicações que exigem altíssimo desempenho e atualizações em tempo real.',
    difficulty: 7.5,
    popularity: 5.0,
  },
  {
    name: 'Dart',
    icon: DartIcon,
    description:
      'Uma linguagem otimizada para o cliente para construir rapidamente apps em qualquer plataforma (Mobile, Web, Desktop).',
    type: 'Linguagem',
    detailedDescription: 'Dart é uma linguagem de programação desenvolvida pelo Google, otimizada para a construção de interfaces de usuário rápidas em qualquer plataforma. Embora seja mais conhecida pelo framework mobile Flutter, Dart também pode compilar para JavaScript, permitindo o desenvolvimento de aplicações web.',
    examples: 'A base do framework Flutter, usado por empresas como Google (Google Ads), BMW, Alibaba.',
    difficulty: 6.5,
    popularity: 7.5,
  },
  {
    name: 'CoffeeScript',
    icon: CoffeescriptIcon,
    description:
      'Uma linguagem que compila para JavaScript, adicionando açúcar sintático inspirado em Ruby e Python.',
    type: 'Linguagem',
    detailedDescription: 'CoffeeScript é uma linguagem de programação que transpila para JavaScript. A ideia é expor as boas partes do JavaScript de uma forma simples. A sintaxe é inspirada em linguagens como Ruby e Python, sendo mais limpa e concisa. Foi muito popular no passado, mas perdeu espaço para o ES6 e TypeScript.',
    examples: 'As primeiras versões do GitHub e Dropbox foram escritas em CoffeeScript.',
    difficulty: 4.5,
    popularity: 1.5,
  },
  {
    name: 'PureScript',
    icon: PurescriptIcon,
    description:
      'Uma linguagem fortemente tipada e puramente funcional que compila para JavaScript legível.',
    type: 'Linguagem',
    detailedDescription: 'PureScript é uma linguagem de programação funcional e estaticamente tipada que compila para JavaScript. Ela se inspira em Haskell e permite que os desenvolvedores escrevam código seguro e expressivo. É uma ótima opção para quem busca os benefícios da programação funcional no ecossistema JavaScript.',
    examples: 'Usado em nichos que exigem alta correção e modelagem de domínio complexa, como fintechs e healthtechs.',
    difficulty: 9.5,
    popularity: 2.0,
  },
  {
    name: 'ReasonML',
    icon: ReasonMLIcon,
    description:
      'Uma sintaxe amigável para a linguagem OCaml, criada pelo Facebook para ser robusta e segura.',
    type: 'Linguagem',
    detailedDescription: 'ReasonML, também conhecido como Reason, é uma nova sintaxe para a linguagem de programação OCaml. Foi criado pelo Facebook com o objetivo de tornar a OCaml, uma linguagem poderosa e segura, mais familiar para desenvolvedores JavaScript. Ele oferece um sistema de tipos robusto e compila para JavaScript rápido e legível.',
    examples: 'Usado para construir partes do Facebook Messenger e WhatsApp.',
    difficulty: 8.7,
    popularity: 2.5,
  },
  {
    name: 'Stimulus',
    icon: StimulusIcon,
    description:
      'Um framework JavaScript modesto para dar vida ao HTML, conectando elementos a objetos JavaScript.',
    type: 'Framework',
    detailedDescription: 'Stimulus é um framework JavaScript com objetivos modestos. Ele não busca assumir toda a sua interface; em vez disso, foi projetado para aprimorar o HTML estático ou renderizado pelo servidor. Você escreve controladores JavaScript e os conecta a elementos em sua página usando atributos HTML simples. É a base do framework Hotwire.',
    examples: 'Basecamp, HEY, e outros produtos da 37signals.',
    difficulty: 3.5,
    popularity: 4.5,
  },
  {
    name: 'ClojureScript',
    icon: ClojurescriptIcon,
    description:
      'Um compilador para Clojure que gera JavaScript, permitindo o uso de uma linguagem Lisp no frontend.',
    type: 'Linguagem',
    detailedDescription: 'ClojureScript é um compilador para Clojure, um dialeto da linguagem Lisp, que compila para JavaScript. Ele permite que os desenvolvedores usem a filosofia e as ferramentas do Clojure (imutabilidade, código como dados) para construir aplicações web no lado do cliente. É conhecido por sua interatividade no desenvolvimento (REPL).',
    examples: 'CircleCI, Nubank, e outras empresas que valorizam a programação funcional e a robustez do ecossistema Lisp.',
    difficulty: 9.0,
    popularity: 3.5,
  },
  {
    name: 'F#',
    icon: FsharpIcon,
    description:
      'Linguagem funcional, de código aberto e multiplataforma que pode compilar para JavaScript usando Fable.',
    type: 'Linguagem',
    detailedDescription: 'F# é uma linguagem de programação funcional, de propósito geral, fortemente tipada, que faz parte do ecossistema .NET. Com o compilador Fable, é possível transpilar código F# para JavaScript, permitindo o desenvolvimento web frontend com os benefícios da programação funcional e do sistema de tipos do F#.',
    examples: 'Empresas que utilizam o ecossistema .NET e desejam aplicar os paradigmas funcionais no frontend.',
    difficulty: 8.8,
    popularity: 2.8,
  },
  {
    name: 'Haxe',
    icon: HaxeIcon,
    description:
      'Uma linguagem de alto nível que pode compilar para JavaScript, C++, Java e outras plataformas.',
    type: 'Linguagem',
    detailedDescription: 'Haxe é um toolkit de código aberto de alto nível baseado em uma linguagem de programação moderna, estaticamente tipada, com sintaxe semelhante a JavaScript e outras linguagens C-like. Uma de suas principais características é a capacidade de compilar para múltiplas plataformas, incluindo JavaScript, C++, Java, C# e mais, a partir de uma única base de código.',
    examples: 'Jogos (Dead Cells), aplicações cross-platform, e ferramentas de linha de comando.',
    difficulty: 7.9,
    popularity: 2.2,
  },
  {
    name: 'Backbone.js',
    icon: BackboneIcon,
    description:
      'Fornece estrutura a aplicações web, fornecendo modelos com vinculação de chave-valor e eventos personalizados.',
    type: 'Biblioteca',
    detailedDescription: 'Backbone.js foi uma das primeiras bibliotecas a trazer uma estrutura MVC (Model-View-Controller) para o JavaScript. Ele fornece modelos (Models) com vinculação de chave-valor, coleções (Collections) com uma rica API de funções enumeráveis, e visões (Views) com manipulação de eventos declarativa. Ajudou a organizar o código de aplicações web complexas antes da era dos frameworks modernos.',
    examples: 'Trello, Airbnb (em suas primeiras versões), Hulu.',
    difficulty: 5.8,
    popularity: 2.0,
  },
  {
    name: 'Knockout.js',
    icon: KnockoutIcon,
    description:
      'Uma biblioteca JavaScript que ajuda a criar interfaces de usuário ricas e responsivas com um modelo de dados subjacente.',
    type: 'Biblioteca',
    detailedDescription: 'Knockout.js é uma biblioteca que simplifica a criação de interfaces de usuário ricas e dinâmicas com JavaScript. Ele usa o padrão MVVM (Model-View-ViewModel) e se baseia em "observáveis" para atualizar automaticamente a UI sempre que o modelo de dados subjacente muda. Foi um pioneiro no conceito de data-binding declarativo.',
    examples: 'Muito popular em aplicações .NET mais antigas (integrado com ASP.NET MVC), e em sistemas que precisavam de data-binding sem um framework completo.',
    difficulty: 6.2,
    popularity: 1.8,
  },
  {
    name: 'Polymer',
    icon: PolymerIcon,
    description:
      'Uma biblioteca do Google para criar aplicativos usando Web Components.',
    type: 'Biblioteca',
    detailedDescription: 'Polymer foi uma biblioteca JavaScript de código aberto do Google para a construção de aplicações web usando Web Components. O projeto visava alavancar os recursos nativos do navegador para permitir a criação de componentes encapsulados e reutilizáveis. Foi um dos pioneiros na popularização dos padrões de Web Components.',
    examples: 'Usado em versões mais antigas do YouTube e Google Play Music.',
    difficulty: 7.0,
    popularity: 1.5,
  },
  {
    name: 'Aurelia',
    icon: AureliaIcon,
    description:
      'Um framework de cliente moderno para web, mobile e desktop, escrito com TypeScript.',
    type: 'Framework',
    detailedDescription: 'Aurelia é um framework JavaScript moderno e flexível para a construção de aplicações web. Ele foca em seguir os padrões da web e em ter uma configuração mínima, sendo "convencional mas não opinativo". Aurelia é escrito em TypeScript e é composto por módulos menores e focados, que podem ser usados juntos ou separadamente.',
    examples: 'Empresas que buscam um framework poderoso mas menos opinativo que o Angular.',
    difficulty: 7.6,
    popularity: 2.5,
  },
  {
    name: 'Meteor',
    icon: MeteorIcon,
    description:
      'Uma plataforma full-stack em JavaScript para desenvolver aplicações web e móveis em tempo real.',
    type: 'Plataforma',
    detailedDescription: 'Meteor é uma plataforma de código aberto para web, mobile e desktop. Ela integra Node.js com outras ferramentas para fornecer uma experiência de desenvolvimento full-stack rápida e fácil. Sua principal característica é a "reatividade de dados", onde as alterações no banco de dados são propagadas automaticamente para todos os clientes conectados em tempo real.',
    examples: 'Qualtrics, PolicyBazaar, e aplicações que necessitam de forte sincronização de dados em tempo real.',
    difficulty: 7.0,
    popularity: 3.8,
  },
  {
    name: 'D3.js',
    icon: D3Icon,
    description:
      'Uma biblioteca JavaScript para manipular documentos com base em dados, criando visualizações de dados dinâmicas.',
    type: 'Biblioteca',
    detailedDescription: 'D3.js (Data-Driven Documents) é uma biblioteca JavaScript para produzir visualizações de dados dinâmicas e interativas em navegadores da web. Ele dá vida aos dados usando HTML, SVG e CSS. A ênfase do D3 nos padrões da web oferece todos os recursos dos navegadores modernos sem se prender a um framework proprietário, combinando poderosas técnicas de visualização com uma abordagem orientada ao DOM.',
    examples: 'The New York Times (para gráficos interativos), visualizações complexas em dashboards de BI.',
    difficulty: 9.0,
    popularity: 6.5,
  },
  {
    name: 'Chart.js',
    icon: ChartjsIcon,
    description:
      'Biblioteca de gráficos simples, porém flexível, para designers e desenvolvedores.',
    type: 'Biblioteca',
    detailedDescription: 'Chart.js é uma biblioteca de gráficos de código aberto para JavaScript que permite a criação de gráficos animados e interativos em aplicações web. É simples de usar e oferece 8 tipos de gráficos diferentes (barras, linhas, pizza, etc.), sendo uma excelente opção para adicionar visualizações de dados de forma rápida e fácil a um projeto.',
    examples: 'Dashboards administrativos, relatórios de analytics e qualquer aplicação que precise de gráficos simples e bonitos.',
    difficulty: 3.0,
    popularity: 8.2,
  },
];

export const backendTechnologies: Technology[] = [
  {
    name: 'Node.js',
    icon: NodeIcon,
    description:
      'Permite executar JavaScript no servidor, ideal para aplicações rápidas e escaláveis.',
    type: 'Plataforma',
    detailedDescription: 'Node.js é um ambiente de execução JavaScript do lado do servidor, construído sobre o motor V8 do Google Chrome. Ele usa um modelo de I/O não bloqueante e orientado a eventos, o que o torna leve e eficiente. É perfeito para aplicações em tempo real que lidam com muitas conexões simultâneas, como chats, APIs e microsserviços.',
    examples: 'Netflix, Uber, PayPal, LinkedIn, Trello.',
    difficulty: 6.5,
    popularity: 9.5,
  },
  {
    name: 'Python',
    icon: PythonIcon,
    description:
      'Versátil e com frameworks poderosos como Django e Flask, ótimo para IA e ciência de dados.',
    type: 'Linguagem',
    detailedDescription: 'Python é uma linguagem de programação de alto nível, interpretada, conhecida por sua sintaxe limpa e legibilidade. No backend, é amplamente utilizada através de frameworks como Django (uma solução completa e robusta) e Flask (um micro-framework flexível). Sua vasta coleção de bibliotecas o torna a escolha número um para ciência de dados, aprendizado de máquina e automação.',
    examples: 'Instagram, Spotify, Google, Dropbox, Reddit (originalmente).',
    difficulty: 4.0,
    popularity: 9.8,
  },
  {
    name: 'Java',
    icon: JavaIcon,
    description:
      'Linguagem robusta e segura, muito usada em sistemas corporativos com o framework Spring.',
    type: 'Linguagem',
    detailedDescription: 'Java é uma linguagem de programação orientada a objetos, class-based, e de propósito geral que é projetada para ter o mínimo de dependências de implementação. É uma das linguagens mais populares para o desenvolvimento de backend corporativo, graças à sua performance, segurança e ao ecossistema maduro, dominado pelo framework Spring, que simplifica a criação de aplicações robustas e escaláveis.',
    examples: 'Amazon, eBay, Alibaba, e a maioria das grandes instituições financeiras e de seguros.',
    difficulty: 7.0,
    popularity: 9.0,
  },
  {
    name: 'Rust',
    icon: RustIcon,
    description:
      'Focado em performance e segurança de memória, ideal para sistemas de alto desempenho.',
    type: 'Linguagem',
    detailedDescription: 'Rust é uma linguagem de programação de sistemas que se concentra em velocidade, segurança de memória e paralelismo. Ela alcança esses objetivos sem a necessidade de um garbage collector (coletor de lixo). É uma excelente escolha para construir serviços de rede de alto desempenho, ferramentas de linha de comando, e sistemas embarcados onde a performance e a confiabilidade são críticas.',
    examples: 'Discord, Figma, Dropbox (para componentes críticos de performance), Microsoft.',
    difficulty: 9.2,
    popularity: 6.8,
  },
  {
    name: 'Go',
    icon: GoIcon,
    description: 'Linguagem do Google focada em simplicidade, concorrência e performance.',
    type: 'Linguagem',
    detailedDescription: 'Go, também conhecida como Golang, é uma linguagem de programação compilada e estaticamente tipada projetada no Google. É conhecida por sua sintaxe limpa, suporte nativo para concorrência (goroutines e channels) e excelente performance. É amplamente utilizada em infraestrutura de nuvem, CLIs e serviços de backend.',
    examples: 'Google, Uber, Twitch, Dropbox, Kubernetes, Docker.',
    difficulty: 6.8,
    popularity: 8.5,
  },
  {
    name: 'C#',
    icon: CsharpIcon,
    description: 'Linguagem moderna e orientada a objetos da Microsoft para o ecossistema .NET.',
    type: 'Linguagem',
    detailedDescription: 'C# é uma linguagem de programação elegante e type-safe, desenvolvida pela Microsoft como parte da iniciativa .NET. É versátil, permitindo criar aplicações web robustas (com ASP.NET), jogos (com Unity), aplicações desktop e mobile. Sua sintaxe é familiar para desenvolvedores C++, Java e JavaScript.',
    examples: 'Microsoft, Stack Overflow, Dell, e muitas aplicações corporativas e de jogos.',
    difficulty: 6.5,
    popularity: 8.8,
  },
  {
    name: 'ASP.NET Core',
    icon: AspNetIcon,
    description: 'Framework de código aberto e multiplataforma para construir aplicações web com C#.',
    type: 'Framework',
    detailedDescription: 'ASP.NET Core é a evolução moderna do ASP.NET. É um framework de alta performance que pode ser executado no Windows, macOS e Linux. Ele é projetado para criar aplicações web e APIs modernas e baseadas em nuvem. É modular, leve e ideal para a construção de microsserviços.',
    examples: 'Microsoft, UPS, e um vasto número de aplicações empresariais.',
    difficulty: 7.2,
    popularity: 8.0,
  },
  {
    name: 'PHP',
    icon: PhpIcon,
    description: 'Linguagem de script do lado do servidor que alimenta uma grande parte da web.',
    type: 'Linguagem',
    detailedDescription: 'PHP é uma linguagem de script de propósito geral amplamente utilizada, especialmente adequada para o desenvolvimento web. É a linguagem por trás do WordPress, o que a torna uma das linguagens mais onipresentes na internet. As versões modernas do PHP são rápidas e incluem muitos recursos de linguagens contemporâneas.',
    examples: 'Facebook (originalmente), WordPress, Wikipedia, Slack, Mailchimp.',
    difficulty: 3.5,
    popularity: 8.2,
  },
  {
    name: 'Laravel',
    icon: LaravelIcon,
    description: 'Um framework PHP com sintaxe expressiva e elegante para desenvolvimento web.',
    type: 'Framework',
    detailedDescription: 'Laravel é um framework de aplicação web com uma sintaxe expressiva e elegante. Ele tenta tirar a dor do desenvolvimento, facilitando tarefas comuns usadas na maioria dos projetos, como autenticação, roteamento, sessões e caching. Laravel visa tornar o processo de desenvolvimento agradável para o desenvolvedor sem sacrificar a funcionalidade da aplicação.',
    examples: '9GAG, BBC, Pfizer, e milhares de aplicações de todos os tamanhos.',
    difficulty: 5.5,
    popularity: 8.5,
  },
  {
    name: 'Ruby',
    icon: RubyIcon,
    description: 'Uma linguagem dinâmica e de código aberto com foco na simplicidade e produtividade.',
    type: 'Linguagem',
    detailedDescription: 'Ruby é uma linguagem de programação interpretada, de alto nível, focada em simplicidade e produtividade. Possui uma sintaxe elegante, natural de ler e fácil de escrever. A filosofia do Ruby é centrada na "felicidade do programador", priorizando a conveniência e a diversão ao escrever código.',
    examples: 'A base do framework Ruby on Rails.',
    difficulty: 5.0,
    popularity: 6.5,
  },
  {
    name: 'Ruby on Rails',
    icon: RailsIcon,
    description: 'Framework opinativo que otimiza a produtividade do desenvolvedor com convenções.',
    type: 'Framework',
    detailedDescription: 'Ruby on Rails, ou apenas Rails, é um framework de desenvolvimento web do lado do servidor escrito em Ruby. Ele segue os princípios de "Convenção sobre Configuração" (CoC) e "Não se Repita" (DRY). Rails é famoso por permitir um desenvolvimento extremamente rápido de aplicações complexas, fornecendo uma estrutura completa com tudo incluído.',
    examples: 'GitHub, Shopify, Airbnb, Hulu, Kickstarter, Basecamp.',
    difficulty: 6.0,
    popularity: 7.0,
  },
  {
    name: 'Express.js',
    icon: ExpressIcon,
    description: 'Framework minimalista e flexível para Node.js, para construção de APIs e aplicações web.',
    type: 'Framework',
    detailedDescription: 'Express.js é um framework de aplicação web para Node.js, de fato o padrão para a maioria das aplicações Node.js. Ele fornece um conjunto robusto de recursos para aplicações web e móveis. Como um framework minimalista, ele não impõe regras rígidas, dando ao desenvolvedor a liberdade de estruturar sua aplicação como preferir.',
    examples: 'IBM, Uber, Accenture, e é o "E" da stack MERN/MEVN.',
    difficulty: 5.0,
    popularity: 9.0,
  },
  {
    name: 'PostgreSQL',
    icon: PostgresqlIcon,
    description: 'Um poderoso sistema de banco de dados relacional de código aberto.',
    type: 'Plataforma',
    detailedDescription: 'PostgreSQL, também conhecido como Postgres, é um sistema de gerenciamento de banco de dados objeto-relacional com ênfase em extensibilidade e conformidade com padrões. É conhecido por sua robustez, conjunto de recursos avançados e forte adesão aos padrões SQL. É uma escolha popular para aplicações que exigem integridade de dados e consultas complexas.',
    examples: 'Apple, Instagram, Spotify, Twitch, Reddit.',
    difficulty: 6.0,
    popularity: 8.7,
  },
  {
    name: 'MongoDB',
    icon: MongodbIcon,
    description: 'Banco de dados NoSQL orientado a documentos, popular por sua flexibilidade e escalabilidade.',
    type: 'Plataforma',
    detailedDescription: 'MongoDB é um banco de dados NoSQL que armazena dados em documentos flexíveis, semelhantes a JSON. Isso significa que os campos podem variar de documento para documento e a estrutura de dados pode ser alterada ao longo do tempo. É ideal para aplicações com requisitos de dados em evolução e para escalar horizontalmente.',
    examples: 'Google, a Forbes, Toyota, Adobe, e como o "M" da stack MERN/MEVN.',
    difficulty: 5.5,
    popularity: 8.9,
  },
  {
    name: 'Django',
    icon: DjangoIcon,
    description:
      'Framework Python de alto nível que incentiva o desenvolvimento rápido e o design limpo e pragmático.',
    type: 'Framework',
    detailedDescription: 'Django é um framework web Python de alto nível que permite o desenvolvimento rápido de sites seguros e de fácil manutenção. Construído por desenvolvedores experientes, ele cuida de grande parte do incômodo do desenvolvimento web, para que você possa se concentrar em escrever seu aplicativo sem precisar reinventar a roda. É gratuito e de código aberto, tem uma comunidade próspera e ativa, ótima documentação e muitas opções de suporte gratuito e pago.',
    examples: 'Instagram, Pinterest, National Geographic, Udemy, NASA.',
    difficulty: 6.8,
    popularity: 9.0,
  },
  {
    name: 'Flask',
    icon: FlaskIcon,
    description:
      'Um microframework Python leve, ideal para criar APIs e aplicações web menores com mais flexibilidade.',
    type: 'Framework',
    detailedDescription: 'Flask é um microframework para Python baseado em Werkzeug, Jinja 2 e boas intenções. É chamado de "micro" porque não exige ferramentas ou bibliotecas particulares. Ele não tem camada de abstração de banco de dados, validação de formulário ou quaisquer outros componentes onde bibliotecas de terceiros preexistentes fornecem funções comuns. No entanto, o Flask suporta extensões que podem adicionar recursos de aplicação como se tivessem sido implementados no próprio Flask.',
    examples: 'Netflix, Reddit (em partes), Twilio, e muitas APIs internas e serviços menores.',
    difficulty: 4.5,
    popularity: 8.2,
  },
  {
    name: 'Spring Boot',
    icon: SpringBootIcon,
    description:
      'Uma extensão do framework Spring que facilita a criação de aplicações Java autônomas e de produção.',
    type: 'Framework',
    detailedDescription: 'O Spring Boot torna fácil a criação de aplicações Spring autônomas e de grau de produção que você pode "simplesmente executar". Ele adota uma visão opinativa da plataforma Spring e de bibliotecas de terceiros, para que você possa começar com o mínimo de barulho. A maioria das aplicações Spring Boot precisa de muito pouca configuração Spring.',
    examples: 'Milhões de desenvolvedores e empresas em todo o mundo, incluindo a Microsoft, Amazon, e Google Cloud.',
    difficulty: 7.5,
    popularity: 9.2,
  },
  {
    name: 'Kotlin',
    icon: KotlinIcon,
    description:
      'Uma linguagem de programação moderna e estaticamente tipada, totalmente interoperável com Java.',
    type: 'Linguagem',
    detailedDescription: 'Kotlin é uma linguagem de programação multiplataforma, estaticamente tipada, de propósito geral, com inferência de tipo. O Kotlin é projetado para interoperar totalmente com Java, e a versão JVM da sua biblioteca padrão depende da Biblioteca de Classes Java, mas a inferência de tipo permite que sua sintaxe seja mais concisa. É a linguagem preferida do Google para desenvolvimento Android e está ganhando tração no desenvolvimento de backend.',
    examples: 'Google, Amazon, Coursera, Atlassian (Jira), e muitas startups de tecnologia.',
    difficulty: 6.8,
    popularity: 8.4,
  },
  {
    name: 'NestJS',
    icon: NestjsIcon,
    description:
      'Um framework Node.js para construir aplicações do lado do servidor eficientes, escaláveis e com TypeScript.',
    type: 'Framework',
    detailedDescription: 'NestJS é um framework para construir aplicações Node.js do lado do servidor eficientes e escaláveis. Ele usa JavaScript progressivo, é construído com e suporta totalmente o TypeScript (ainda permite que os desenvolvedores codifiquem em JavaScript puro) e combina elementos de POO (Programação Orientada a Objetos), PF (Programação Funcional) e PRF (Programação Reativa Funcional). Ele usa Express por baixo dos panos, mas também fornece compatibilidade com outros frameworks como o Fastify.',
    examples: 'Adidas, Autodesk, Roche, e um número crescente de empresas que adotam TypeScript no backend.',
    difficulty: 7.2,
    popularity: 7.8,
  },
  {
    name: 'Elixir',
    icon: ElixirIcon,
    description:
      'Uma linguagem dinâmica e funcional projetada para construir aplicações escaláveis e de fácil manutenção.',
    type: 'Linguagem',
    detailedDescription: 'Elixir é uma linguagem dinâmica e funcional projetada para construir aplicações escaláveis e de fácil manutenção. Elixir roda na Erlang VM, conhecida por executar sistemas de baixa latência, distribuídos e tolerantes a falhas, sendo usada em telecomunicações, bancos, e-commerce, mensagens instantâneas e muito mais. A sintaxe do Elixir é amigável e inspirada em Ruby.',
    examples: 'WhatsApp (usa a Erlang VM), Discord, Pinterest, Bleacher Report.',
    difficulty: 8.5,
    popularity: 5.5,
  },
  {
    name: 'Phoenix',
    icon: PhoenixIcon,
    description:
      'Um framework de desenvolvimento web escrito em Elixir que implementa o padrão MVC do lado do servidor.',
    type: 'Framework',
    detailedDescription: 'Phoenix é um framework web construído sobre a linguagem de programação Elixir e roda na Erlang VM. Ele implementa o padrão Model-View-Controller (MVC) do lado do servidor. Phoenix é projetado para construir aplicações de alta performance e em tempo real, aproveitando a concorrência e a tolerância a falhas da plataforma Erlang.',
    examples: 'Financial Times, Bleacher Report, e empresas que necessitam de alta concorrência e tempo real.',
    difficulty: 8.0,
    popularity: 5.0,
  },
  {
    name: 'MySQL',
    icon: MysqlIcon,
    description:
      'O sistema de gerenciamento de banco de dados relacional de código aberto mais popular do mundo.',
    type: 'Plataforma',
    detailedDescription: 'MySQL é um sistema de gerenciamento de banco de dados relacional (RDBMS) de código aberto. Seu nome é uma combinação de "My", o nome da filha do co-fundador Michael Widenius, e "SQL", a abreviação de Structured Query Language. É um componente central da pilha de software de código aberto LAMP (Linux, Apache, MySQL, Perl/PHP/Python) e é usado por muitos aplicativos web baseados em banco de dados, incluindo o WordPress.',
    examples: 'Facebook, YouTube, Twitter, Booking.com, GitHub, NASA.',
    difficulty: 4.0,
    popularity: 9.7,
  },
  {
    name: 'Redis',
    icon: RedisIcon,
    description:
      'Um armazenamento de estrutura de dados em memória, usado como banco de dados, cache e message broker.',
    type: 'Plataforma',
    detailedDescription: 'Redis é um armazenamento de estrutura de dados em memória de código aberto (licenciado pela BSD), usado como banco de dados, cache e message broker. Ele suporta estruturas de dados como strings, hashes, listas, conjuntos, conjuntos ordenados com consultas de intervalo, bitmaps, hyperloglogs, índices geoespaciais e streams. Redis tem replicação integrada, scripts Lua, remoção LRU, transações e diferentes níveis de persistência em disco.',
    examples: 'Twitter, GitHub, Snapchat, Stack Overflow, para caching e gerenciamento de sessões.',
    difficulty: 5.8,
    popularity: 8.8,
  },
  {
    name: 'Docker',
    icon: DockerIcon,
    description:
      'Uma plataforma para desenvolver, enviar e executar aplicações em contêineres.',
    type: 'Ferramenta',
    detailedDescription: 'Docker é um conjunto de produtos de plataforma como serviço (PaaS) que usam virtualização em nível de sistema operacional para entregar software em pacotes chamados contêineres. Contêineres são isolados uns dos outros e agrupam seu próprio software, bibliotecas e arquivos de configuração; eles podem se comunicar uns com os outros através de canais bem definidos. Isso garante que as aplicações funcionem de forma consistente em diferentes ambientes de desenvolvimento, teste e produção.',
    examples: 'PayPal, Netflix, Adobe, e praticamente todas as empresas de tecnologia modernas para CI/CD e implantação.',
    difficulty: 6.5,
    popularity: 9.9,
  },
  {
    name: 'Firebase',
    icon: FirebaseIcon,
    description: 'Uma plataforma do Google que fornece serviços de backend, como banco de dados, autenticação e mais.',
    type: 'Plataforma',
    detailedDescription: 'Firebase é uma plataforma de desenvolvimento de aplicativos móveis e da web que fornece aos desenvolvedores uma infinidade de ferramentas e serviços para ajudá-los a desenvolver aplicativos de alta qualidade, aumentar sua base de usuários e ganhar mais dinheiro. Os serviços cobrem funcionalidades como banco de dados NoSQL (Firestore), autenticação, armazenamento de arquivos, hosting e funções serverless.',
    examples: 'Alibaba, The New York Times, Duolingo, e milhões de outros aplicativos.',
    difficulty: 4.5,
    popularity: 9.4,
  },
  {
    name: 'Supabase',
    icon: SupabaseIcon,
    description: 'A alternativa de código aberto ao Firebase. Adicione um backend ao seu projeto em minutos.',
    type: 'Plataforma',
    detailedDescription: 'Supabase é uma plataforma que oferece um backend completo a partir de um banco de dados PostgreSQL. Ele fornece um estúdio de banco de dados, APIs instantâneas (REST e GraphQL), autenticação, armazenamento de objetos e muito mais. Por ser construído sobre ferramentas de código aberto, oferece mais flexibilidade e portabilidade em comparação com soluções proprietárias.',
    examples: 'Adoção crescente em startups e projetos que preferem uma pilha de código aberto.',
    difficulty: 5.0,
    popularity: 7.8,
  },
  {
    name: 'Nginx',
    icon: NginxIcon,
    description: 'Um servidor web de alto desempenho, também usado como proxy reverso, cache e balanceador de carga.',
    type: 'Ferramenta',
    detailedDescription: 'Nginx é um software de servidor web que também pode ser usado como proxy reverso, balanceador de carga, proxy de email e cache HTTP. É conhecido por sua alta performance, estabilidade, rico conjunto de recursos, configuração simples e baixo consumo de recursos. É uma peça fundamental na arquitetura de muitos sites de alto tráfego.',
    examples: 'Mais da metade dos sites mais movimentados da internet, incluindo Netflix, Airbnb e Zappos.',
    difficulty: 7.0,
    popularity: 9.6,
  },
  {
    name: 'Apache Kafka',
    icon: ApacheKafkaIcon,
    description: 'Uma plataforma de streaming de eventos distribuída para pipelines de dados em tempo real e aplicações.',
    type: 'Ferramenta',
    detailedDescription: 'Apache Kafka é uma plataforma de streaming de eventos distribuída de código aberto usada por milhares de empresas para pipelines de dados de alto desempenho, análise de streaming, integração de dados e aplicações mission-critical. Ela permite a publicação e assinatura de fluxos de registros, seu armazenamento de forma tolerante a falhas e seu processamento em tempo real.',
    examples: 'LinkedIn, Uber, Netflix, Spotify, para processamento de eventos em larga escala.',
    difficulty: 8.8,
    popularity: 8.0,
  },
  {
    name: 'RabbitMQ',
    icon: RabbitmqIcon,
    description: 'Um dos message brokers mais populares, que ajuda a escalar aplicações e evitar gargalos.',
    type: 'Ferramenta',
    detailedDescription: 'RabbitMQ é um message broker (intermediário de mensagens) de código aberto. De forma simples, ele aceita e encaminha mensagens. Você pode pensar nele como uma agência de correios: quando você coloca a correspondência em uma caixa de correio, pode ter certeza de que o carteiro eventualmente a entregará ao destinatário. RabbitMQ é usado para desacoplar e escalar aplicações, permitindo a comunicação assíncrona entre serviços.',
    examples: 'JPMorgan, NASA, e inúmeras aplicações que utilizam arquitetura de microsserviços.',
    difficulty: 7.5,
    popularity: 7.9,
  },
  {
    name: 'Kubernetes',
    icon: KubernetesIcon,
    description: 'Plataforma de orquestração de contêineres para automatizar a implantação, o dimensionamento e o gerenciamento de aplicações.',
    type: 'Ferramenta',
    detailedDescription: 'Kubernetes, ou K8s, é um sistema de código aberto para automatizar a implantação, o dimensionamento e o gerenciamento de aplicações em contêineres. Ele agrupa contêineres que compõem uma aplicação em unidades lógicas para fácil gerenciamento e descoberta. Foi originalmente projetado pelo Google e agora é mantido pela Cloud Native Computing Foundation.',
    examples: 'Google, Spotify, Capital One, e a maioria das empresas que usam contêineres em produção.',
    difficulty: 9.0,
    popularity: 9.5,
  },
  {
    name: 'Terraform',
    icon: TerraformIcon,
    description: 'Ferramenta de infraestrutura como código (IaC) para construir, alterar e versionar infraestrutura com segurança e eficiência.',
    type: 'Ferramenta',
    detailedDescription: 'Terraform é uma ferramenta de software de infraestrutura como código criada pela HashiCorp. Os usuários definem e provisionam a infraestrutura de data center usando uma linguagem de configuração declarativa conhecida como HashiCorp Configuration Language (HCL), ou opcionalmente JSON. Ele suporta uma infinidade de provedores de nuvem como AWS, Azure e Google Cloud.',
    examples: 'Usado por inúmeras empresas para gerenciar sua infraestrutura em nuvem de forma declarativa.',
    difficulty: 7.8,
    popularity: 8.9,
  },
  {
    name: 'gRPC',
    icon: GrpcIcon,
    description: 'Um framework de Remote Procedure Call (RPC) de código aberto de alto desempenho, inicialmente desenvolvido pelo Google.',
    type: 'Ferramenta',
    detailedDescription: 'gRPC é um framework moderno de RPC que pode ser executado em qualquer ambiente. Ele pode conectar serviços em e através de data centers com suporte conectável para balanceamento de carga, rastreamento, verificação de saúde e autenticação. Ele usa HTTP/2 para transporte, Protocol Buffers como a linguagem de descrição de interface, e fornece recursos como autenticação, streaming bidirecional e controle de fluxo.',
    examples: 'Netflix, Square, e para comunicação interna de microsserviços de alto desempenho.',
    difficulty: 8.2,
    popularity: 7.5,
  },
  {
    name: 'Solidity',
    icon: SolidityIcon,
    description: 'A linguagem de programação mais popular para escrever contratos inteligentes (smart contracts).',
    type: 'Linguagem',
    detailedDescription: 'Solidity é uma linguagem de programação orientada a objetos para escrever contratos inteligentes. É usada para implementação de contratos inteligentes em várias plataformas de blockchain, mais notavelmente, Ethereum. Sua sintaxe é semelhante a C++ e JavaScript.',
    examples: 'A base de milhares de projetos de DeFi, NFTs e outras aplicações descentralizadas (dApps) no ecossistema Ethereum.',
    difficulty: 8.7,
    popularity: 6.0,
  },
  {
    name: 'Scala',
    icon: ScalaIcon,
    description: 'Uma linguagem que combina programação orientada a objetos e funcional em um pacote conciso e de alto nível.',
    type: 'Linguagem',
    detailedDescription: 'Scala é uma linguagem de programação de propósito geral que fornece suporte para programação funcional e um forte sistema de tipo estático. Projetada para ser concisa, muitas das decisões de design da Scala visavam abordar as críticas ao Java. O código-fonte da Scala é destinado a ser compilado para bytecode Java, para que o código Scala resultante seja executado na JVM (Java Virtual Machine).',
    examples: 'Twitter, LinkedIn, The Guardian, e em sistemas de big data com Apache Spark.',
    difficulty: 9.3,
    popularity: 5.8,
  },
  {
    name: 'Akka',
    icon: AkkaIcon,
    description: 'Um toolkit para construir aplicações altamente concorrentes, distribuídas e resilientes na JVM.',
    type: 'Framework',
    detailedDescription: 'Akka é um toolkit e tempo de execução de código aberto para construir aplicações altamente concorrentes, distribuídas e tolerantes a falhas em Java e Scala. Akka usa o Modelo de Atores para simplificar a escrita de software concorrente e paralelo. Os atores fornecem um nível de abstração que torna mais fácil escrever, testar e manter aplicações concorrentes.',
    examples: 'LinkedIn, PayPal, e empresas que lidam com processamento massivo de dados e eventos.',
    difficulty: 9.5,
    popularity: 4.5,
  },
  {
    name: 'Cassandra',
    icon: CassandraIcon,
    description: 'Um banco de dados NoSQL distribuído, de código aberto, projetado para lidar com grandes quantidades de dados.',
    type: 'Plataforma',
    detailedDescription: 'Apache Cassandra é um sistema de gerenciamento de banco de dados NoSQL distribuído, de código aberto e gratuito, projetado para lidar com grandes quantidades de dados em muitos servidores commodity, proporcionando alta disponibilidade sem ponto único de falha. Cassandra oferece suporte robusto para clusters que abrangem vários data centers.',
    examples: 'Netflix, Apple, Instagram, Spotify, Uber.',
    difficulty: 8.5,
    popularity: 7.2,
  },
  {
    name: 'Elasticsearch',
    icon: ElasticsearchIcon,
    description: 'Um motor de busca e análise distribuído e RESTful, construído sobre o Apache Lucene.',
    type: 'Ferramenta',
    detailedDescription: 'Elasticsearch é o coração da Elastic Stack, um conjunto de ferramentas de código aberto para ingestão, enriquecimento, armazenamento, análise e visualização de dados. Comumente usado para busca de texto completo, análise de logs, monitoramento de infraestrutura e análise de segurança. É conhecido por sua velocidade e escalabilidade.',
    examples: 'Netflix, Microsoft, Goldman Sachs, e para a função de busca em muitos sites como o Stack Overflow.',
    difficulty: 7.9,
    popularity: 8.6,
  },
  {
    name: 'Prometheus',
    icon: PrometheusIcon,
    description: 'Um toolkit de monitoramento e alerta de sistemas de código aberto, originalmente construído na SoundCloud.',
    type: 'Ferramenta',
    detailedDescription: 'Prometheus é uma solução de monitoramento que coleta e armazena suas métricas como dados de séries temporais, ou seja, informações de métricas são armazenadas com o timestamp em que foram registradas. Ele usa um modelo de pull HTTP para coletar métricas de sistemas-alvo. É uma ferramenta fundamental no ecossistema de observabilidade nativo da nuvem.',
    examples: 'DigitalOcean, SoundCloud, e amplamente usado em conjunto com Kubernetes.',
    difficulty: 7.7,
    popularity: 8.3,
  },
];
